### ISSUE TITLE
library for virtual-network

### ISSUE THREAD

**Issue by fhrdina1** [beakerlib/libraries#15]
Hi,
I want to upstream internal library virtual-network. Can you create the "virtual-network" repository for me? Is there anything else needed?

cc: @mruprich

**Comment by hegerj** [comment]
Created and I added you as a maintainer.

**Comment by fhrdina1** [comment]
Can you also add @mruprich as the repository maintainer, @hegerj, please? I think I can't do it with my current permissions.

**Comment by hegerj** [comment]
Are you sure? Maintainer is the second highest level of permission.
Try going https://github.com/beakerlib/virtual-network/settings/access here and see if you can see `Add people` button.

**Comment by fhrdina1** [comment]
I am getting 404 when opening that link.

**Comment by hegerj** [comment]
Weird. I added Michal. Anything else?

**Comment by fhrdina1** [comment]
That's all. Thank you.
