### ISSUE TITLE
Opensourcing and upstreaming tuned library for better world

### ISSUE THREAD

**Issue by RHEmployee** [beakerlib/libraries#2]
Hello. I would like to opensource tuned basic library, which is used by many tuned tests.

First step seems to open issue and ask for new repository (different repository is recommended).

Would you please create repository: tuned for storing tuned beaker library please?

Thank you and have a nice day.

**Comment by psss** [comment]
The new repo has been created:

 * https://github.com/beakerlib/tuned

You have been invited as admin.

**Comment by sopos** [comment]
added the repo permissions also to librarians and gatekeepers
