### ISSUE TITLE
library for bind

### ISSUE THREAD

**Issue by psklenar** [beakerlib/libraries#7]
there is library:
/CoreOS/bind/Library/bind-utils
Description: Few helpers for working with DNS and DNSSEC in tests.

whats needed to have it as an open-source library?

ccing @pemensik

**Comment by sopos** [comment]
* you should definitely check if there are no internal references (hostname, mount points, etc.)
* pick a repo name - I guess it would be _bind_ but it may be something more generic - it's up to you
* we will create the repo and assign proper permissions
* then you are good to go

**Comment by pemensik** [comment]
I think *bind* name is okay. Simular to tuned/basic, there might be bind/utils and bind/setup, similar to /CoreOS/bind/Library/bind-utils and /CoreOS/bind/Library/bind-setup. Setup part is not too much useful, but I guess we can sort that out inside the new repository. *bind/utils* should be useful to more DNS related software implementations than just bind. But that is up to users.

**Comment by psklenar** [comment]
+1 for 'bind' name

**Comment by sopos** [comment]
An empty repository [1] was created for you.

Note, it is actually not necessary to create a directory structure for a library if it is going to be just one, e.g. `library(bind)` in the root should work as well. However, feel free to organize your libraries as you wish, also deeper structure should work, e.g. `library(bind/path/to/a/library)` for a library in _path/to/a/library_.

@psklenar, @pemensik, Don't forget to accept in [2], it expires at some point.

1. https://github.com/beakerlib/bind
2. https://github.com/beakerlib/bind/invitations
