### ISSUE TITLE
sos library

### ISSUE THREAD

**Issue by Madeyro** [beakerlib/libraries#8]
Hello,
I would like to open source the library `/CoreOS/sos/Library/utils`.
As the name `utils` is not very specific, I think we can go with `sos`.

CC: @mkluson

**Comment by psss** [comment]
Seems there already is a `sos` repository: https://github.com/beakerlib/sos

**Comment by Madeyro** [comment]
mhradilek found that our library is already opensourced /o\ 
Would it be possible to give us access to this repository please?

https://github.com/beakerlib/sos/blob/master/utils/lib.sh

**Comment by psss** [comment]
@Madeyro and @mkluson added permissions.
